# SPDX-FileCopyrightText: 2025 Benjamin Nakaten (GFZ) <bnakaten@gfz.de>
# SPDX-FileCopyrightText: 2025 GFZ Helmholtz Centre for Geosciences
#
# SPDX-License-Identifier: CC0-1.0

name: gmlGUI_dev
channels:
  - conda-forge
dependencies:
  - python
  - flask
  - gdal
  - geos
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyevtk
  - pyvista
  - pyyaml
  - scipy
  - streamlit
  - pip:
      - stpyvista
